version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BASE_MODEL_ID=unsloth/Llama-3.2-1B-Instruct-bnb-4bit
      - ADAPTER_MODEL_ID=SaptarshiNag18/email_summarizer_llama3.2-1b_4bit

  frontend:
    build:
      context: ./frontend/vite-project
      
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend